[package]
name = "toold-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "toold"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
libc.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
toold-core = { path = "../toold-core" }
tracing.workspace = true
tracing-subscriber.workspace = true
